# CHAPTER 2 - The Tools of the Trade in Quantum Computing - PennyWise Code


*Note*: You may skip the following three cells if you have alredy installed the right versions of all the libraries mentioned in *Appendix D*. This will likely NOT be the case if you are running this notebook on a cloud service such as Google Colab.




In [19]:
import pennylane as qml
import numpy as np

In [45]:
dev = qml.device('lightning.qubit', wires = 2)

In [46]:
def qc(theta):
    qml.PauliX(wires=0)
    qml.Hadamard(wires=0)
    qml.RX(theta, wires=1)
    return qml.probs()
qcirc = qml.QNode(qc, dev)

total = []
for theta in np.linspace(0, 2*np.pi, 100):
    total.append(qcirc(theta))

total

[array([0.5, 0. , 0.5, 0. ]),
 array([0.49949667, 0.00050333, 0.49949667, 0.00050333]),
 array([0.4979887, 0.0020113, 0.4979887, 0.0020113]),
 array([0.49548217, 0.00451783, 0.49548217, 0.00451783]),
 array([0.49198718, 0.00801282, 0.49198718, 0.00801282]),
 array([0.48751778, 0.01248222, 0.48751778, 0.01248222]),
 array([0.48209198, 0.01790802, 0.48209198, 0.01790802]),
 array([0.47573163, 0.02426837, 0.47573163, 0.02426837]),
 array([0.46846234, 0.03153766, 0.46846234, 0.03153766]),
 array([0.46031338, 0.03968662, 0.46031338, 0.03968662]),
 array([0.45131756, 0.04868244, 0.45131756, 0.04868244]),
 array([0.44151111, 0.05848889, 0.44151111, 0.05848889]),
 array([0.43093351, 0.06906649, 0.43093351, 0.06906649]),
 array([0.41962735, 0.08037265, 0.41962735, 0.08037265]),
 array([0.40763817, 0.09236183, 0.40763817, 0.09236183]),
 array([0.39501423, 0.10498577, 0.39501423, 0.10498577]),
 array([0.38180637, 0.11819363, 0.38180637, 0.11819363]),
 array([0.36806777, 0.13193223, 0.36806777, 0.

In [47]:
print(qml.draw(qcirc)(theta=2))

0: ──X─────────H─┤  Probs
1: ──RX(2.00)────┤  Probs
